### ISSUE TITLE
add support for customizing server port

### ISSUE THREAD

**Issue by thescientist13** [thescientist13/git-explorer#12]
## Type of Change
- [x] New Feature Request
- [ ] Documentation
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Currently the project is hardcoded to open on port `3000`.

## Details
User should be able to pass the port as an environment variable when starting the [`git-explorer` [command](https://github.com/thescientist13/git-explorer/blob/master/bin/index.js) / server.
```shell
$ npx git-explorer --port 1981
```

**Comment by sowmiyamuthuraman** [comment]
Hii, I would like to work on this! Is it fine to use `yargs` for parsing the command line arguments

**Comment by thescientist13** [comment]
Hi @sowmiyamuthuraman , thanks for your interest in the project.  I would be happy to see a PR for this and using `yargs` would be fine me with me!  👍 

If you have any questions, please feel to free ask them here.
