### ISSUE TITLE
open option not working

### ISSUE THREAD

**Issue by thescientist13** [thescientist13/git-explorer#27]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
After the latest release (0.5.0) the `--open` flag is not working.
```
$ npx git-explorer --port=4200 --open
npx: installed 93 in 6.176s
Cannot find module 'open'
```

## Details
Related to #7 , the issue / solution seems pretty straightforward.  The **open** package needs to be a `dependency`.  Currently it is a `devDependency` in _package.json_.
```json
{
  ...
  
   "dependencies": {
    ...
    "yargs": "^15.0.2"
  },
  "devDependencies": {
    "copy": "^0.3.2",
    "eslint": "^6.7.1",
    "open": "^7.0.0",
    "rimraf": "^3.0.0"
  }
}
```

**Comment by thescientist13** [comment]
My apologies @sowmiyamuthuraman , I should have caught this in the PR review.  Simple enough fix though, I'll get a PR and new version up ASAP.

**Comment by thescientist13** [comment]
Success 🏆 
```
$ npx git-explorer --port=4200 --open
npx: installed 95 in 5.538s
Git Explorer now running at localhost:4200
```

**Comment by sowmiyamuthuraman** [comment]
> My apologies @sowmiyamuthuraman , I should have caught this in the PR review. Simple enough fix though, I'll get a PR and new version up ASAP.

Sry I have missed that

**Comment by thescientist13** [comment]
No worries!  0.5.1 should now be in npm with both of your new changes in it.  Seems to be working great for me.  Thanks for your help!
