### ISSUE TITLE
automatically open the browser

### ISSUE THREAD

**Issue by thescientist13** [thescientist13/git-explorer#7]
## Type of Change
- [x] New Feature Request
- [ ] Documentation
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Right now when the server starts, there is literally no messaging
```shell
$ npm start

> git-explorer@0.1.0 start /Users/owenbuckley/Workspace/github/repos/git-explorer
> node .
```

## Details
Would be nice to at least tell the user what port to open, or even better, open it for them!

**Comment by sowmiyamuthuraman** [comment]
I would like to work on this!

**Comment by thescientist13** [comment]
That would be great, thanks so much @sowmiyamuthuraman !  🙌

**Comment by thescientist13** [comment]
as a note, I added you as a collaborator to the project, so you can clone and push branches instead of having to fork.  👍
